### ISSUE TITLE
semi-supervised scripts

### ISSUE THREAD

**Issue by 15091444119** [joelmoniz/BLISS#3]
How could we perform semi-supervised training using your code? Could you provide an example script?

**Comment by 15091444119** [comment]
How could we perform semi-supervised training using your code? Could you provide an example script?

**Comment by codedecde** [comment]
Hi 
[Here](https://github.com/joelmoniz/BLISS/blob/master/configs/config.yaml) is the config for the semi-supervised learning. You can run the code by using, after installing all the dependencies.
```md
python -m bliss.main --config_file ./configs/config.yaml --gpu True
```
Let us know if you have any further questions :)

**Comment by 15091444119** [comment]
> Hi
> [Here](https://github.com/joelmoniz/BLISS/blob/master/configs/config.yaml) is the config for the semi-supervised learning. You can run the code by using, after installing all the dependencies.
> 
> ```lisp
> python -m bliss.main --config_file ./configs/config.yaml --gpu True
> ```
> 
> Let us know if you have any further questions :)

Thanks a lot !
